"""add_updated_at_to_stage_runs

Revision ID: 7fac5ae0e6ed
Revises: af125c9d90fb
Create Date: 2026-01-28 15:09:44.201534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fac5ae0e6ed'
down_revision: Union[str, Sequence[str], None] = 'af125c9d90fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_document_stage_runs', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False))
    op.add_column('workflow_stage_runs', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_stage_runs', 'updated_at')
    op.drop_column('workflow_document_stage_runs', 'updated_at')
    # ### end Alembic commands ###
