"""add workflow_name to workflows

Revision ID: 7fc246d7dcc3
Revises: 386691f5f63c
Create Date: 2026-01-27 14:07:00.907965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc246d7dcc3'
down_revision: Union[str, Sequence[str], None] = '386691f5f63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('workflow_name', sa.String(), nullable=False, server_default='Untitled'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'workflow_name')
    # ### end Alembic commands ###
