"""add stage_metadata to stage runs

Revision ID: af125c9d90fb
Revises: ee9d8a7edede
Create Date: 2026-01-28 13:25:53.327993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af125c9d90fb'
down_revision: Union[str, Sequence[str], None] = 'ee9d8a7edede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_document_stage_runs', sa.Column('stage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_stage_runs', sa.Column('stage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_stage_runs', 'stage_metadata')
    op.drop_column('workflow_document_stage_runs', 'stage_metadata')
    # ### end Alembic commands ###
