"""add_idempotency_keys_to_extractions_and_relationships

Revision ID: d3775e797d90
Revises: bdfe5b4439e5
Create Date: 2026-03-16 22:51:12.884403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3775e797d90'
down_revision: Union[str, Sequence[str], None] = 'bdfe5b4439e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'clause_reference',
               existing_type=sa.VARCHAR(length=255),
               comment="Clause reference e.g., 'SECTION II.B.3' or 'Endorsement CA 20 48'",
               existing_comment='Clause reference e.g., SECTION II.B.3 or Endorsement CA 20 48',
               existing_nullable=True)
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_primary_page'), table_name='citations')
    op.drop_index(op.f('ix_citations_source_type'), table_name='citations')
    op.alter_column('document_chunks', 'effective_section_type',
               existing_type=sa.VARCHAR(),
               comment='Effective section for extraction routing (may differ from section_type for endorsements)',
               existing_comment='Projected section type (e.g., Coverages for endorsements)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'semantic_role',
               existing_type=sa.VARCHAR(),
               comment='Semantic role: coverage_modifier, exclusion_modifier, both, administrative_only, etc.',
               existing_comment='Semantic role of the chunk (e.g., coverage_modifier)',
               existing_nullable=True)
    op.drop_column('document_chunks', 'original_section_type')
    op.drop_column('document_chunks', 'additional_metadata')
    op.add_column('entity_relationships', sa.Column('idempotency_key', sa.String(), nullable=True, comment='Deterministic key for idempotent relationship extraction'))
    op.create_index(op.f('ix_entity_relationships_idempotency_key'), 'entity_relationships', ['idempotency_key'], unique=True)
    op.add_column('section_extractions', sa.Column('idempotency_key', sa.String(), nullable=True, comment='Deterministic key for idempotent extraction'))
    op.create_index(op.f('ix_section_extractions_idempotency_key'), 'section_extractions', ['idempotency_key'], unique=True)
    op.alter_column('users', 'supabase_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_vector_embeddings_canonical_entity_id'), table_name='vector_embeddings')
    op.drop_index(op.f('ix_vector_embeddings_entity_type'), table_name='vector_embeddings')
    op.drop_index(op.f('ix_vector_embeddings_source_chunk_id'), table_name='vector_embeddings', postgresql_where='(source_chunk_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vector_embeddings_source_chunk_id'), 'vector_embeddings', ['source_chunk_id'], unique=False, postgresql_where='(source_chunk_id IS NOT NULL)')
    op.create_index(op.f('ix_vector_embeddings_entity_type'), 'vector_embeddings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_vector_embeddings_canonical_entity_id'), 'vector_embeddings', ['canonical_entity_id'], unique=False)
    op.alter_column('users', 'supabase_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_section_extractions_idempotency_key'), table_name='section_extractions')
    op.drop_column('section_extractions', 'idempotency_key')
    op.drop_index(op.f('ix_entity_relationships_idempotency_key'), table_name='entity_relationships')
    op.drop_column('entity_relationships', 'idempotency_key')
    op.add_column('document_chunks', sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional chunk metadata'))
    op.add_column('document_chunks', sa.Column('original_section_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Structural section type before projection'))
    op.alter_column('document_chunks', 'semantic_role',
               existing_type=sa.VARCHAR(),
               comment='Semantic role of the chunk (e.g., coverage_modifier)',
               existing_comment='Semantic role: coverage_modifier, exclusion_modifier, both, administrative_only, etc.',
               existing_nullable=True)
    op.alter_column('document_chunks', 'effective_section_type',
               existing_type=sa.VARCHAR(),
               comment='Projected section type (e.g., Coverages for endorsements)',
               existing_comment='Effective section for extraction routing (may differ from section_type for endorsements)',
               existing_nullable=True)
    op.create_index(op.f('ix_citations_source_type'), 'citations', ['source_type'], unique=False)
    op.create_index(op.f('ix_citations_primary_page'), 'citations', ['primary_page'], unique=False)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.alter_column('citations', 'clause_reference',
               existing_type=sa.VARCHAR(length=255),
               comment='Clause reference e.g., SECTION II.B.3 or Endorsement CA 20 48',
               existing_comment="Clause reference e.g., 'SECTION II.B.3' or 'Endorsement CA 20 48'",
               existing_nullable=True)
    # ### end Alembic commands ###
