"""add_document_name_col_to_documents_table

Revision ID: ee9d8a7edede
Revises: 7fc246d7dcc3
Create Date: 2026-01-28 00:43:26.152008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9d8a7edede'
down_revision: Union[str, Sequence[str], None] = '7fc246d7dcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_name')
    # ### end Alembic commands ###
