"""add_page_analysis_tables

Revision ID: 2c713aae6b0d
Revises: b0d6b10e408f
Create Date: 2025-12-13 18:59:46.178439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c713aae6b0d'
down_revision: Union[str, Sequence[str], None] = 'b0d6b10e408f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False, comment='1-indexed page number'),
    sa.Column('top_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='First 5-10 lines of text from page'),
    sa.Column('text_density', sa.Numeric(precision=5, scale=3), nullable=False, comment='Text density ratio (0.0 to 1.0)'),
    sa.Column('has_tables', sa.Boolean(), nullable=False, comment='Whether page contains tables'),
    sa.Column('max_font_size', sa.Numeric(precision=6, scale=2), nullable=True, comment='Largest font size (indicates headers)'),
    sa.Column('page_hash', sa.String(length=64), nullable=False, comment='Hash for duplicate detection'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_analysis_doc_page'),
    comment='Lightweight page signals for classification'
    )
    op.create_table('page_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False, comment='1-indexed page number'),
    sa.Column('page_type', sa.String(length=50), nullable=False, comment='declarations | coverages | conditions | exclusions | endorsement | sov | loss_run | invoice | boilerplate | duplicate | unknown'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=3), nullable=False, comment='Classification confidence (0.0 to 1.0)'),
    sa.Column('should_process', sa.Boolean(), nullable=False, comment='Whether to perform full OCR on this page'),
    sa.Column('duplicate_of', sa.Integer(), nullable=True, comment='Page number this is a duplicate of'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='Human-readable classification reasoning'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_classification_doc_page'),
    comment='Page classification results'
    )
    op.create_table('page_manifests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False, comment='Total number of pages in document'),
    sa.Column('pages_to_process', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of page numbers to process'),
    sa.Column('pages_skipped', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of page numbers to skip'),
    sa.Column('processing_ratio', sa.Numeric(precision=5, scale=3), nullable=False, comment='Percentage of pages to process (0.0 to 1.0)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    comment='Page processing manifest for cost optimization'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_manifests')
    op.drop_table('page_classifications')
    op.drop_table('page_analysis')
    # ### end Alembic commands ###
