"""create workflow outputs

Revision ID: 386691f5f63c
Revises: fd3022570b79
Create Date: 2026-01-12 01:29:39.873536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '386691f5f63c'
down_revision: Union[str, Sequence[str], None] = 'fd3022570b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_definition_id', sa.UUID(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=False, comment='Denormalized workflow name for quick queries'),
    sa.Column('status', sa.String(), nullable=False, comment='COMPLETED, COMPLETED_WITH_WARNINGS, FAILED, NEEDS_REVIEW'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True, comment='Overall confidence score (0.0-1.0)'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Workflow-specific output payload'),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context (HITL flags, warnings, etc.)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Generic storage for all product workflow outputs'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_outputs')
    # ### end Alembic commands ###
