"""add_workflow_user_and_relationship_document_ids

Revision ID: 604f751d5b05
Revises: f2d4d5b1054b
Create Date: 2026-01-09 16:06:40.398375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604f751d5b05'
down_revision: Union[str, Sequence[str], None] = 'f2d4d5b1054b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_relationships', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'entity_relationships', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # Clear existing embeddings as they are incompatible with new workflow-scoped model
    op.execute("DELETE FROM vector_embeddings")
    op.add_column('vector_embeddings', sa.Column('workflow_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('vector_embeddings_doc_idx'), table_name='vector_embeddings')
    op.drop_index(op.f('vector_embeddings_embedding_idx'), table_name='vector_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('vector_embeddings_entity_idx'), table_name='vector_embeddings')
    op.drop_index(op.f('vector_embeddings_location_idx'), table_name='vector_embeddings', postgresql_where='(location_id IS NOT NULL)')
    op.drop_index(op.f('vector_embeddings_section_idx'), table_name='vector_embeddings')
    op.create_foreign_key(None, 'vector_embeddings', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vector_embeddings', 'workflow_type')
    op.add_column('workflows', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'user_id')
    op.add_column('vector_embeddings', sa.Column('workflow_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.create_index(op.f('vector_embeddings_section_idx'), 'vector_embeddings', ['section_type'], unique=False)
    op.create_index(op.f('vector_embeddings_location_idx'), 'vector_embeddings', ['location_id'], unique=False, postgresql_where='(location_id IS NOT NULL)')
    op.create_index(op.f('vector_embeddings_entity_idx'), 'vector_embeddings', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('vector_embeddings_embedding_idx'), 'vector_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('vector_embeddings_doc_idx'), 'vector_embeddings', ['document_id'], unique=False)
    op.drop_column('vector_embeddings', 'workflow_id')
    op.drop_constraint(None, 'entity_relationships', type_='foreignkey')
    op.drop_column('entity_relationships', 'document_id')
    # ### end Alembic commands ###
