"""sync_schema_changes

Revision ID: b0d6b10e408f
Revises: a1b2c3d4e5f6
Create Date: 2025-12-05 20:34:31.237522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d6b10e408f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_canonical_entities_key'), table_name='canonical_entities')
    op.drop_index(op.f('idx_chunk_embeddings_chunk'), table_name='chunk_embeddings')
    op.drop_index(op.f('idx_chunk_entity_chunk'), table_name='chunk_entity_mentions')
    op.drop_index(op.f('idx_document_entity_document'), table_name='document_entity_links')
    op.add_column('document_pages', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('document_pages', sa.Column('markdown', sa.Text(), nullable=True))
    op.add_column('document_pages', sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('loss_run_claims', sa.Column('chunk_id', sa.UUID(), nullable=True))
    op.add_column('loss_run_claims', sa.Column('policy_number', sa.String(), nullable=True, comment='Associated policy number'))
    op.add_column('loss_run_claims', sa.Column('report_date', sa.Date(), nullable=True, comment='Date claim was reported'))
    op.add_column('loss_run_claims', sa.Column('description', sa.Text(), nullable=True, comment='Claim description'))
    op.create_foreign_key(None, 'loss_run_claims', 'document_chunks', ['chunk_id'], ['id'])
    op.alter_column('normalized_chunks', 'source_stage',
               existing_type=sa.VARCHAR(),
               comment='Pipeline stage that created this (normalization, extraction, etc.)',
               existing_comment='Pipeline stage that created this',
               existing_nullable=True)
    op.add_column('sov_items', sa.Column('chunk_id', sa.UUID(), nullable=True))
    op.add_column('sov_items', sa.Column('address', sa.Text(), nullable=True, comment='Property address'))
    op.add_column('sov_items', sa.Column('building_limit', sa.Numeric(), nullable=True, comment='Building coverage limit'))
    op.add_column('sov_items', sa.Column('contents_limit', sa.Numeric(), nullable=True, comment='Contents coverage limit'))
    op.add_column('sov_items', sa.Column('bi_limit', sa.Numeric(), nullable=True, comment='Business interruption limit'))
    op.add_column('sov_items', sa.Column('total_insured_value', sa.Numeric(), nullable=True, comment='Total insured value (TIV)'))
    op.create_foreign_key(None, 'sov_items', 'document_chunks', ['chunk_id'], ['id'])
    op.drop_column('sov_items', 'limit')
    op.drop_column('sov_items', 'deductible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sov_items', sa.Column('deductible', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Deductible amount'))
    op.add_column('sov_items', sa.Column('limit', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Coverage limit'))
    op.drop_constraint(None, 'sov_items', type_='foreignkey')
    op.drop_column('sov_items', 'total_insured_value')
    op.drop_column('sov_items', 'bi_limit')
    op.drop_column('sov_items', 'contents_limit')
    op.drop_column('sov_items', 'building_limit')
    op.drop_column('sov_items', 'address')
    op.drop_column('sov_items', 'chunk_id')
    op.alter_column('normalized_chunks', 'source_stage',
               existing_type=sa.VARCHAR(),
               comment='Pipeline stage that created this',
               existing_comment='Pipeline stage that created this (normalization, extraction, etc.)',
               existing_nullable=True)
    op.drop_constraint(None, 'loss_run_claims', type_='foreignkey')
    op.drop_column('loss_run_claims', 'description')
    op.drop_column('loss_run_claims', 'report_date')
    op.drop_column('loss_run_claims', 'policy_number')
    op.drop_column('loss_run_claims', 'chunk_id')
    op.drop_column('document_pages', 'additional_metadata')
    op.drop_column('document_pages', 'markdown')
    op.drop_column('document_pages', 'text')
    op.create_index(op.f('idx_document_entity_document'), 'document_entity_links', ['document_id'], unique=False)
    op.create_index(op.f('idx_chunk_entity_chunk'), 'chunk_entity_mentions', ['chunk_id'], unique=False)
    op.create_index(op.f('idx_chunk_embeddings_chunk'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('idx_canonical_entities_key'), 'canonical_entities', ['entity_type', 'canonical_key'], unique=False)
    # ### end Alembic commands ###
