"""replace_document_readiness_with_workflow_stage_tracking

Revision ID: e133764c790e
Revises: d4234f6ce12a
Create Date: 2026-01-05 18:12:40.275508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e133764c790e'
down_revision: Union[str, Sequence[str], None] = 'd4234f6ce12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_document_stage_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'document_id', 'stage_name', name='uq_workflow_doc_stage'),
    comment='Document-level stage tracking within a workflow'
    )
    op.execute('DROP TABLE IF EXISTS "quotes" CASCADE')
    op.execute('DROP TABLE IF EXISTS "extracted_fields" CASCADE')
    op.execute('DROP TABLE IF EXISTS "insured_entities" CASCADE')
    op.execute('DROP TABLE IF EXISTS "policy_comparisons" CASCADE')
    op.execute('DROP TABLE IF EXISTS "policy_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "claim_entities" CASCADE')
    op.execute('DROP TABLE IF EXISTS "document_readiness" CASCADE')
    op.execute('DROP TABLE IF EXISTS "chunk_embeddings" CASCADE')
    op.execute('DROP TABLE IF EXISTS "exclusion_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "embedding_sync_state" CASCADE')
    op.execute('DROP TABLE IF EXISTS "invoice_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "ocr_results" CASCADE')
    op.execute('DROP TABLE IF EXISTS "kyc_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "coverage_items" CASCADE')
    op.drop_index(op.f('ix_normalized_chunks_content_hash'), table_name='normalized_chunks')
    op.drop_index(op.f('ix_normalized_chunks_pipeline_run_id'), table_name='normalized_chunks')
    op.execute('DROP TABLE IF EXISTS "chunk_entity_links" CASCADE')
    op.execute('DROP TABLE IF EXISTS "chunk_entity_mentions" CASCADE')
    op.execute('DROP TABLE IF EXISTS "normalized_chunks" CASCADE')
    op.execute('DROP TABLE IF EXISTS "document_raw_text" CASCADE')
    op.execute('DROP TABLE IF EXISTS "document_classifications" CASCADE')
    op.execute('DROP TABLE IF EXISTS "endorsement_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "carrier_entities" CASCADE')
    op.execute('DROP TABLE IF EXISTS "claim_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "submissions" CASCADE')
    op.execute('DROP TABLE IF EXISTS "graph_sync_state" CASCADE')
    op.execute('DROP TABLE IF EXISTS "financial_analysis" CASCADE')
    op.execute('DROP TABLE IF EXISTS "claims" CASCADE')
    op.execute('DROP TABLE IF EXISTS "proposals" CASCADE')
    op.execute('DROP TABLE IF EXISTS "condition_items" CASCADE')
    op.execute('DROP TABLE IF EXISTS "property_sov" CASCADE')
    op.execute('DROP TABLE IF EXISTS "ocr_tokens" CASCADE')
    op.execute('DROP TABLE IF EXISTS "document_entity_links" CASCADE')
    op.execute('DROP TABLE IF EXISTS "chunk_classification_signals" CASCADE')
    op.execute('DROP TABLE IF EXISTS "policy_entities" CASCADE')
    op.drop_index(op.f('ix_document_tables_document_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_page_number'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_table_type'), table_name='document_tables')
    op.drop_column('documents', 'stage_extracted')
    op.drop_column('documents', 'stage_classified')
    op.drop_column('documents', 'stage_enriched')
    op.drop_column('documents', 'stage_summarized')
    op.drop_column('documents', 'stage_processed')
    op.drop_index(op.f('ix_entity_evidence_canonical_entity_id'), table_name='entity_evidence')
    op.drop_index(op.f('ix_entity_evidence_entity_mention_id'), table_name='entity_evidence')
    op.drop_index(op.f('ix_entity_mentions_document_id_entity_type'), table_name='entity_mentions')
    op.drop_column('entity_relationships', 'document_id')
    op.add_column('section_extractions', sa.Column('workflow_id', sa.UUID(), nullable=False))
    op.alter_column('section_extractions', 'pipeline_run_id',
               existing_type=sa.VARCHAR(),
               comment='Pipeline execution identifier',
               existing_nullable=True)
    op.drop_index(op.f('ix_section_extractions_document_id_section_type'), table_name='section_extractions')
    op.create_foreign_key(None, 'section_extractions', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_workflow_documents_workflow_document_unique'), table_name='workflow_documents', postgresql_where='(workflow_id IS NOT NULL)')
    op.create_unique_constraint('uq_workflow_stage_run', 'workflow_stage_runs', ['workflow_id', 'stage_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workflow_stage_run', 'workflow_stage_runs', type_='unique')
    op.create_index(op.f('idx_workflow_documents_workflow_document_unique'), 'workflow_documents', ['workflow_id', 'document_id'], unique=True, postgresql_where='(workflow_id IS NOT NULL)')
    op.drop_constraint(None, 'section_extractions', type_='foreignkey')
    op.create_index(op.f('ix_section_extractions_document_id_section_type'), 'section_extractions', ['document_id', 'section_type'], unique=False)
    op.alter_column('section_extractions', 'pipeline_run_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Pipeline execution identifier',
               existing_nullable=True)
    op.drop_column('section_extractions', 'workflow_id')
    op.add_column('entity_relationships', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_entity_mentions_document_id_entity_type'), 'entity_mentions', ['document_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entity_evidence_entity_mention_id'), 'entity_evidence', ['entity_mention_id'], unique=False)
    op.create_index(op.f('ix_entity_evidence_canonical_entity_id'), 'entity_evidence', ['canonical_entity_id'], unique=False)
    op.add_column('documents', sa.Column('stage_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Processed stage: page analysis, OCR, tables, chunking complete'))
    op.add_column('documents', sa.Column('stage_summarized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Summarized stage: vector embeddings, graph construction complete'))
    op.add_column('documents', sa.Column('stage_enriched', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Enriched stage: entity resolution, relationships, validation complete'))
    op.add_column('documents', sa.Column('stage_classified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Classified stage: document and section classification complete'))
    op.add_column('documents', sa.Column('stage_extracted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Extracted stage: section fields, tables, entities extracted'))
    op.create_index(op.f('ix_document_tables_table_type'), 'document_tables', ['table_type'], unique=False)
    op.create_index(op.f('ix_document_tables_page_number'), 'document_tables', ['document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_tables_document_id'), 'document_tables', ['document_id'], unique=False)
    op.create_table('policy_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='1:1 FK to canonical_entities.id'),
    sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Policy number'),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True, comment='Policy effective date'),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True, comment='Policy expiration date'),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Entity confidence'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['canonical_entities.id'], name=op.f('policy_entities_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_entities_pkey')),
    comment='Typed canonical entity table for policies'
    )
    op.create_table('chunk_classification_signals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('signals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Per-class confidence scores: {policy: 0.12, claim: 0.78, ...}'),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Extracted keywords/phrases indicating document type'),
    sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Extracted entities: policy_number, claim_number, dates, amounts'),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='LLM confidence in signal extraction'),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Classifier model version'),
    sa.Column('pipeline_run_id', sa.UUID(), autoincrement=False, nullable=True, comment='Links to specific pipeline execution'),
    sa.Column('source_stage', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Pipeline stage: classification'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('chunk_classification_signals_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chunk_classification_signals_pkey'))
    )
    op.create_table('document_entity_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canonical_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Linking confidence'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['canonical_entity_id'], ['canonical_entities.id'], name=op.f('document_entity_links_canonical_entity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_entity_links_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_entity_links_pkey'))
    )
    op.create_table('ocr_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('x_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], name=op.f('ocr_tokens_document_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ocr_tokens_pkey'))
    )
    op.create_table('property_sov',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sov_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('property_sov_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('property_sov_pkey'))
    )
    op.create_table('condition_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('condition_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type of condition'),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Condition title'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Full description'),
    sa.Column('applies_to', sa.VARCHAR(), autoincrement=False, nullable=True, comment='What it applies to'),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of requirements'),
    sa.Column('consequences', sa.TEXT(), autoincrement=False, nullable=True, comment='Consequences of non-compliance'),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Section reference'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('condition_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('condition_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('condition_items_pkey'))
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('proposal_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('proposals_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('proposals_pkey'))
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('claim_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('insured_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loss_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('loss_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('claims_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claims_pkey'))
    )
    op.create_table('financial_analysis',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('extracted_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('financial_analysis_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('financial_analysis_pkey'))
    )
    op.create_table('graph_sync_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_table', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Table name: canonical_entities, entity_relationships, etc.'),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False, comment='Record ID in source table'),
    sa.Column('neo4j_node_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Neo4j internal node/relationship ID'),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Last successful sync time'),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=False, comment='pending, synced, failed'),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message if sync failed'),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_sync_state_pkey'))
    )
    op.create_table('chunk_entity_mentions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Type of entity mentioned'),
    sa.Column('raw_value', sa.TEXT(), autoincrement=False, nullable=False, comment='Original text as it appears in chunk'),
    sa.Column('normalized_value', sa.TEXT(), autoincrement=False, nullable=True, comment='Cleaned/standardized value'),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Detection confidence (0.0-1.0)'),
    sa.Column('span_start', sa.INTEGER(), autoincrement=False, nullable=True, comment='Character offset start'),
    sa.Column('span_end', sa.INTEGER(), autoincrement=False, nullable=True, comment='Character offset end'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['normalized_chunks.id'], name=op.f('chunk_entity_mentions_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chunk_entity_mentions_pkey'))
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('submission_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('insured_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('submissions_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submissions_pkey'))
    )
    op.create_table('claim_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('claim_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Claim identifier'),
    sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Associated policy number'),
    sa.Column('claimant_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Name of claimant'),
    sa.Column('loss_date', sa.DATE(), autoincrement=False, nullable=True, comment='Date of loss'),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=True, comment='Date claim was reported'),
    sa.Column('claim_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type of claim'),
    sa.Column('loss_description', sa.TEXT(), autoincrement=False, nullable=True, comment='Description of loss'),
    sa.Column('loss_location', sa.TEXT(), autoincrement=False, nullable=True, comment='Location of loss'),
    sa.Column('claim_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Claimed amount'),
    sa.Column('paid_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Amount paid'),
    sa.Column('reserve_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Reserve amount'),
    sa.Column('claim_status', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Status (Open, Closed, etc.)'),
    sa.Column('adjuster_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Name of adjuster'),
    sa.Column('denial_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Reason for denial'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('claim_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('claim_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_items_pkey'))
    )
    op.create_table('carrier_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='1:1 FK to canonical_entities.id'),
    sa.Column('canonical_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Canonical carrier name'),
    sa.Column('normalized_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Normalized name for matching'),
    sa.Column('naic', sa.VARCHAR(), autoincrement=False, nullable=True, comment='NAIC code'),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Entity confidence'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['canonical_entities.id'], name=op.f('carrier_entities_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carrier_entities_pkey')),
    comment='Typed canonical entity table for insurance carriers'
    )
    op.create_table('endorsement_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('endorsement_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Endorsement identifier'),
    sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Associated policy number'),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True, comment='Endorsement effective date'),
    sa.Column('change_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type of change (Addition, Deletion, Modification)'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Description of change'),
    sa.Column('premium_change', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Premium impact (positive or negative)'),
    sa.Column('coverage_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Coverage modifications'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('endorsement_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('endorsement_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('endorsement_items_pkey'))
    )
    op.create_table('document_classifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('classified_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('classifier_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('decision_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Aggregation details: scores, method, chunks_used, fallback_used'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_classifications_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_classifications_pkey'))
    )
    op.create_table('chunk_entity_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canonical_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Linking confidence'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['canonical_entity_id'], ['canonical_entities.id'], name=op.f('chunk_entity_links_canonical_entity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['normalized_chunks.id'], name=op.f('chunk_entity_links_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chunk_entity_links_pkey'))
    )
    op.create_table('document_raw_text',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], name=op.f('document_raw_text_document_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_raw_text_pkey'))
    )
    op.create_table('normalized_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('normalized_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('normalization_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Structured entity mentions extracted from chunk'),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Structured relationships between entities'),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='SHA256 hash of normalized_text for change detection'),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='LLM/normalizer version for provenance'),
    sa.Column('prompt_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Prompt template version used'),
    sa.Column('pipeline_run_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Pipeline execution identifier'),
    sa.Column('source_stage', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Pipeline stage that created this (normalization, extraction, etc.)'),
    sa.Column('quality_score', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Confidence/quality metric for normalization'),
    sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When extraction was performed'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name='normalized_chunks_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='normalized_chunks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_normalized_chunks_pipeline_run_id'), 'normalized_chunks', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_normalized_chunks_content_hash'), 'normalized_chunks', ['content_hash'], unique=False)
    op.create_table('coverage_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('coverage_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Name of coverage'),
    sa.Column('coverage_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type/category'),
    sa.Column('limit_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Coverage limit'),
    sa.Column('deductible_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Deductible amount'),
    sa.Column('premium_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Premium for this coverage'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Coverage description'),
    sa.Column('sub_limits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Sub-limits'),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Specific exclusions'),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Specific conditions'),
    sa.Column('per_occurrence', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Is per occurrence'),
    sa.Column('aggregate', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Is aggregate limit'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('coverage_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('coverage_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coverage_items_pkey'))
    )
    op.create_table('kyc_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Customer/Entity name'),
    sa.Column('customer_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type (Individual/Entity)'),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True, comment='DOB for individuals'),
    sa.Column('incorporation_date', sa.DATE(), autoincrement=False, nullable=True, comment='Incorporation date for entities'),
    sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Tax ID / SSN / EIN'),
    sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Business type'),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Industry sector'),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True, comment='Full address'),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True, comment='City'),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True, comment='State'),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True, comment='ZIP code'),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Country'),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Phone number'),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Email address'),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Website URL'),
    sa.Column('identification_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='ID type'),
    sa.Column('identification_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='ID number'),
    sa.Column('identification_issuer', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Issuing authority'),
    sa.Column('identification_expiry', sa.DATE(), autoincrement=False, nullable=True, comment='ID expiry date'),
    sa.Column('authorized_signers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of authorized signers'),
    sa.Column('ownership_structure', sa.TEXT(), autoincrement=False, nullable=True, comment='Ownership details'),
    sa.Column('annual_revenue', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Annual revenue'),
    sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='Number of employees'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('kyc_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('kyc_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kyc_items_pkey'))
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ocr_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='OCR engine version'),
    sa.Column('pipeline_run_id', sa.UUID(), autoincrement=False, nullable=True, comment='Links to specific pipeline execution'),
    sa.Column('source_stage', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Pipeline stage: ocr'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('ocr_results_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ocr_results_pkey'))
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Invoice identifier'),
    sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Associated policy number'),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True, comment='Invoice date'),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True, comment='Payment due date'),
    sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Total invoice amount'),
    sa.Column('amount_paid', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Amount paid to date'),
    sa.Column('balance_due', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Remaining balance'),
    sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Status (Paid, Pending, Overdue)'),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Payment method if paid'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('invoice_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('invoice_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_items_pkey'))
    )
    op.create_table('embedding_sync_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_embedding_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When embedding was last generated'),
    sa.Column('embedding_model', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Model used'),
    sa.Column('embedding_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Version used'),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=False, comment='pending, synced, failed'),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message if sync failed'),
    sa.ForeignKeyConstraint(['chunk_id'], ['normalized_chunks.id'], name=op.f('embedding_sync_state_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('embedding_sync_state_pkey'))
    )
    op.create_table('exclusion_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('exclusion_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type of exclusion'),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Exclusion title'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Full description'),
    sa.Column('applies_to', sa.VARCHAR(), autoincrement=False, nullable=True, comment='What it applies to'),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Scope (Total/Partial)'),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Exceptions to exclusion'),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=True, comment='Reason for exclusion'),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Section reference'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('exclusion_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('exclusion_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exclusion_items_pkey'))
    )
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Model name: text-embedding-3-large, etc.'),
    sa.Column('embedding_version', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Model version for tracking updates'),
    sa.Column('embedding_dimension', sa.INTEGER(), autoincrement=False, nullable=False, comment='Vector dimension: 1536, 3072, etc.'),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='JSONB array of floats representing the vector'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['normalized_chunks.id'], name=op.f('chunk_embeddings_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chunk_embeddings_pkey'))
    )
    op.create_table('document_readiness',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('classified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('classified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('extracted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('enriched', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enriched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('summarized', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('summarized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-01-01 18:03:19.500879+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-01-01 18:03:19.500879+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_readiness_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_readiness_pkey')),
    sa.UniqueConstraint('document_id', name=op.f('document_readiness_document_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('claim_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='1:1 FK to canonical_entities.id'),
    sa.Column('claim_number', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Claim number'),
    sa.Column('loss_date', sa.DATE(), autoincrement=False, nullable=True, comment='Loss date'),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Entity confidence'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['canonical_entities.id'], name=op.f('claim_entities_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_entities_pkey')),
    comment='Typed canonical entity table for claims'
    )
    op.create_table('policy_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Policy identification number'),
    sa.Column('policy_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Type of policy (Property, Auto, GL, etc.)'),
    sa.Column('insured_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Name of insured party'),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True, comment='Policy effective date'),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True, comment='Policy expiration date'),
    sa.Column('premium_amount', sa.NUMERIC(), autoincrement=False, nullable=True, comment='Total premium'),
    sa.Column('coverage_limits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Coverage limits by type'),
    sa.Column('deductibles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Deductibles by coverage type'),
    sa.Column('carrier_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Insurance carrier'),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Agent/broker name'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional fields'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('policy_items_chunk_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('policy_items_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_items_pkey'))
    )
    op.create_table('policy_comparisons',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comparison_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('policy_comparisons_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_comparisons_pkey'))
    )
    op.create_table('insured_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='1:1 FK to canonical_entities.id'),
    sa.Column('canonical_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Canonical insured name'),
    sa.Column('normalized_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Normalized name for matching'),
    sa.Column('primary_address', sa.TEXT(), autoincrement=False, nullable=True, comment='Primary address'),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Entity confidence'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['canonical_entities.id'], name=op.f('insured_entities_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insured_entities_pkey')),
    comment='Typed canonical entity table for insured parties'
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('extracted_fields_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extracted_fields_pkey'))
    )
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('carrier_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('premium', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-13 13:44:58.72424+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('quotes_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quotes_pkey'))
    )
    op.drop_table('workflow_document_stage_runs')
    # ### end Alembic commands ###
