"""add_vector_embeddings

Revision ID: f2d4d5b1054b
Revises: 7780c664de30
Create Date: 2026-01-07 20:42:01.819657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f2d4d5b1054b'
down_revision: Union[str, Sequence[str], None] = '7780c664de30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('vector_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('embedded_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Canonical table for pgvector embeddings'
    )
    
    # Vector and metadata indexes
    op.create_index(
        'vector_embeddings_embedding_idx', 
        'vector_embeddings', 
        ['embedding'], 
        postgresql_using='ivfflat', 
        postgresql_with={'lists': 100}, 
        postgresql_ops={'embedding': 'vector_cosine_ops'}
    )
    op.create_index('vector_embeddings_doc_idx', 'vector_embeddings', ['document_id'])
    op.create_index('vector_embeddings_section_idx', 'vector_embeddings', ['section_type'])
    op.create_index('vector_embeddings_entity_idx', 'vector_embeddings', ['entity_type', 'entity_id'])
    op.create_index(
        'vector_embeddings_location_idx', 
        'vector_embeddings', 
        ['location_id'], 
        postgresql_where=sa.text('location_id IS NOT NULL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_embeddings')
    # ### end Alembic commands ###
