"""replace_clerk_id_with_supabase_user_id

Revision ID: fd3022570b79
Revises: 604f751d5b05
Create Date: 2026-01-11 14:25:46.467622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3022570b79'
down_revision: Union[str, Sequence[str], None] = '604f751d5b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_user_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['supabase_user_id'])
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'supabase_user_id')
    # ### end Alembic commands ###
