"""Prompts package for centralized LLM prompt management."""

from app.prompts.system_prompts import (
    UNIFIED_BATCH_EXTRACTION_PROMPT,
    SECTION_EXTRACTION_PROMPT,
    RELATIONSHIP_EXTRACTION_PROMPT,
    SINGLE_CHUNK_NORMALIZATION_PROMPT,
    SIMPLE_NORMALIZATION_PROMPT,
    VALID_ENTITY_TYPES,
    VALID_SECTION_TYPES,
    VALID_RELATIONSHIP_TYPES,
)

__all__ = [
    "UNIFIED_BATCH_EXTRACTION_PROMPT",
    "SECTION_EXTRACTION_PROMPT",
    "RELATIONSHIP_EXTRACTION_PROMPT",
    "SINGLE_CHUNK_NORMALIZATION_PROMPT",
    "VALID_ENTITY_TYPES",
    "VALID_SECTION_TYPES",
    "VALID_RELATIONSHIP_TYPES",
]
