"""Quote Comparison configuration package."""

from app.temporal.product.quote_comparison.configs.quote_comparison import (
    CONFIG,
    REQUIRED_SECTIONS,
    REQUIRED_ENTITIES,
    PROCESSING_CONFIG,
    WORKFLOW_NAME,
    WORKFLOW_VERSION,
    WORKFLOW_DISPLAY_NAME,
    WORKFLOW_DESCRIPTION,
    MIN_DOCUMENTS,
    MAX_DOCUMENTS,
    QUALITY_SCORE_WEIGHTS,
    COVERAGE_CATEGORIES,
    NUMERIC_FIELDS_CONFIG,
    EXCLUDED_FIELDS,
)

__all__ = [
    "CONFIG",
    "REQUIRED_SECTIONS",
    "REQUIRED_ENTITIES",
    "PROCESSING_CONFIG",
    "WORKFLOW_NAME",
    "WORKFLOW_VERSION",
    "WORKFLOW_DISPLAY_NAME",
    "WORKFLOW_DESCRIPTION",
    "MIN_DOCUMENTS",
    "MAX_DOCUMENTS",
    "QUALITY_SCORE_WEIGHTS",
    "COVERAGE_CATEGORIES",
    "NUMERIC_FIELDS_CONFIG",
    "EXCLUDED_FIELDS",
]
